<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ingreso De Datos</title>
</head>
<body>
    <form action="GET.PHP" method="get">
    Nombre: 
    <br><input type="text" name="Nombre"><br>
    Correo:
    <br><input type="email" name="Correo"><br>
    Edad:
    <br><input type="Numero" name="Edad"><br>
    </form>

    <?php
    $_GET 


</body>
</html>